#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64
"malkukhu@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle12c.cs.torontomu.ca )( Port=1521))(CONNECT_DATA=(SID=orcl12c)))" <<EOF

DROP TABLE ALERTS CASCADE CONSTRAINTS;
DROP TABLE ENVIRONMENTAL_SENSORS CASCADE CONSTRAINTS;
DROP TABLE MAINTENANCE CASCADE CONSTRAINTS;
DROP TABLE PERFORMANCE_METRICS CASCADE CONSTRAINTS;
DROP TABLE SERVERS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

exit;
EOF
